# Generated by Django 4.1 on 2022-08-29 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drb_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=30)),
                ("date_created", models.DateField(default=datetime.date(2022, 8, 29))),
            ],
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("date_created", models.DateField(default=datetime.date(2022, 8, 29))),
            ],
        ),
        migrations.CreateModel(
            name="DiscountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("discount_qty", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ParametersModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter", models.CharField(max_length=20)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StoreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(blank=True, max_length=100)),
                ("date_created", models.DateField(default=datetime.date(2022, 8, 29))),
            ],
        ),
        migrations.CreateModel(
            name="UnitsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_label", models.CharField(max_length=10)),
            ],
        ),
    ]
