# Generated by Django 4.1 on 2022-08-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drb_app", "0002_brandmodel_categorymodel_discountmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMetaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(default="", max_length=10)),
                ("nic", models.CharField(default="", max_length=10)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "sale_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("priority", models.IntegerField(default=0)),
                ("on_sale", models.BooleanField(default=False)),
                ("popular", models.BooleanField(default=False)),
                ("strong", models.BooleanField(default=False)),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="of_brand",
                        to="drb_app.brandmodel",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="of_category",
                        to="drb_app.categorymodel",
                    ),
                ),
                (
                    "discount",
                    models.ManyToManyField(
                        related_name="has_discounts", to="drb_app.discountmodel"
                    ),
                ),
                (
                    "nic_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="has_nic_unit",
                        to="drb_app.unitsmodel",
                    ),
                ),
                (
                    "size_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="has_size_unit",
                        to="drb_app.unitsmodel",
                    ),
                ),
            ],
        ),
    ]
