# Generated by Django 4.1 on 2022-09-02 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drb_app", "0005_productmetamodel_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmetamodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="brandmodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 2)),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 2)),
        ),
        migrations.AlterField(
            model_name="disposablemodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 2)),
        ),
        migrations.AlterField(
            model_name="juicemodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 2)),
        ),
        migrations.AlterField(
            model_name="podmodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 2)),
        ),
        migrations.AlterField(
            model_name="productmetamodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 2)),
        ),
        migrations.AlterField(
            model_name="storemodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 2)),
        ),
    ]
