# Generated by Django 4.1 on 2022-09-03 00:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "drb_app",
            "0006_productmetamodel_image_alter_brandmodel_date_created_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DisposableStockModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(model_name="disposablemodel", name="stock",),
        migrations.RemoveField(model_name="juicemodel", name="stock",),
        migrations.RemoveField(model_name="podmodel", name="stock",),
        migrations.AlterField(
            model_name="brandmodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 3)),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 3)),
        ),
        migrations.AlterField(
            model_name="disposablemodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 3)),
        ),
        migrations.AlterField(
            model_name="juicemodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 3)),
        ),
        migrations.AlterField(
            model_name="podmodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 3)),
        ),
        migrations.AlterField(
            model_name="productmetamodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 3)),
        ),
        migrations.AlterField(
            model_name="storemodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 3)),
        ),
        migrations.DeleteModel(name="StockModel",),
        migrations.AddField(
            model_name="disposablestockmodel",
            name="disposable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drb_app.disposablemodel",
            ),
        ),
        migrations.AddField(
            model_name="disposablestockmodel",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drb_app.storemodel",
            ),
        ),
    ]
