# Generated by Django 4.1 on 2022-09-03 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drb_app", "0007_disposablestockmodel_remove_disposablemodel_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodStockModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "disposable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drb_app.podmodel",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drb_app.storemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JuiceStockModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "disposable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drb_app.juicemodel",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drb_app.storemodel",
                    ),
                ),
            ],
        ),
    ]
