# Generated by Django 4.1 on 2022-09-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drb_app", "0009_rename_disposable_juicestockmodel_juice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablemodel",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="juicemodel",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="podmodel",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
