# Generated by Django 4.1 on 2022-09-08 20:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drb_app", "0011_disposablemodel_image_juicemodel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandmodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),
        migrations.AlterField(
            model_name="disposablemodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),
        migrations.AlterField(
            model_name="juicemodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),
        migrations.AlterField(
            model_name="podmodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),
        migrations.AlterField(
            model_name="productmetamodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),
        migrations.AlterField(
            model_name="storemodel",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),

    ]
