# Generated by Django 4.1 on 2022-09-08 21:28

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drb_app", "0012_alter_brandmodel_date_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flavour",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10), size=None
                    ),
                ),
                (
                    "flav_count",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(null=True), size=None
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("qty", models.IntegerField(default=0)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 9, 8, 21, 28, 55, 842354)
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drb_app.productmetamodel",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drb_app.storemodel",
                    ),
                ),
            ],
        ),
    ]
